In [125]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt #for plotting the data 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn import metrics
import missingno as msno
import pandas_profiling
%matplotlib inline

In [126]:
data=pd.read_csv('customer data.csv')

In [127]:
data.shape

(168, 188)

In [128]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Columns: 188 entries, fraudulent to transactions/14/transactionFailed
dtypes: bool(1), float64(23), object(164)
memory usage: 245.7+ KB

In [129]:
data.head()

,fraudulent,customer/customerEmail,customer/customerPhone,customer/customerDevice,customer/customerIPAddress,customer/customerBillingAddress,orders/0/orderId,orders/0/orderAmount,orders/0/orderState,orders/0/orderShippingAddress,...,transactions/13/transactionId,transactions/13/orderId,transactions/13/paymentMethodId,transactions/13/transactionAmount,transactions/13/transactionFailed,transactions/14/transactionId,transactions/14/orderId,transactions/14/paymentMethodId,transactions/14/transactionAmount,transactions/14/transactionFailed
0,False,josephhoward@yahoo.com,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\r\nBrownside, CA 51896",vjbdvd,18.0,pending,"5493 Jones Islands\r\nBrownside, CA 51896",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,True,evansjeffery@yahoo.com,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,356 Elizabeth Inlet Suite 120\r\nPort Joshuabu...,nlghpa,45.0,fulfilled,"898 Henry Ports\r\nNew Keithview, CA 95893-2497",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,andersonwilliam@yahoo.com,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\r\nDavisberg, PR 72250",yk34y2,33.0,failed,"8478 Sean Ridges Apt. 441\r\nDavisberg, PR 72250",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,rubenjuarez@yahoo.com,670.664.8168x94985,slovx60t0i558may4ks0,95de:8565:5a66:792c:26e0:6cfb:7d87:11af,"7769 Elizabeth Bridge Apt. 343\r\nNortonstad, ...",fbz9ep,34.0,fulfilled,"7769 Elizabeth Bridge Apt. 343\r\nNortonstad, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,True,uchen@malone.com,1-981-877-0870,j0pd24k5h8dl2fqu0cz4,196.89.235.192,148 Russell Lodge Apt. 445\r\nPort Jennifersid...,56h7iw,71.0,fulfilled,148 Russell Lodge Apt. 445\r\nPort Jennifersid...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
data.columns

Index(['fraudulent', 'customer/customerEmail', 'customer/customerPhone',
       'customer/customerDevice', 'customer/customerIPAddress',
       'customer/customerBillingAddress', 'orders/0/orderId',
       'orders/0/orderAmount', 'orders/0/orderState',
       'orders/0/orderShippingAddress',
       ...
       'transactions/13/transactionId', 'transactions/13/orderId',
       'transactions/13/paymentMethodId', 'transactions/13/transactionAmount',
       'transactions/13/transactionFailed', 'transactions/14/transactionId',
       'transactions/14/orderId', 'transactions/14/paymentMethodId',
       'transactions/14/transactionAmount',
       'transactions/14/transactionFailed'],
      dtype='object', length=188)

In [131]:
data.describe()

,orders/0/orderAmount,orders/1/orderAmount,transactions/0/transactionAmount,transactions/1/transactionAmount,orders/2/orderAmount,transactions/2/transactionAmount,transactions/3/transactionAmount,transactions/4/transactionAmount,orders/3/orderAmount,orders/4/orderAmount,...,transactions/6/transactionAmount,transactions/7/transactionAmount,orders/7/orderAmount,transactions/8/transactionAmount,transactions/9/transactionAmount,transactions/10/transactionAmount,transactions/11/transactionAmount,transactions/12/transactionAmount,transactions/13/transactionAmount,transactions/14/transactionAmount
count,141.000000,116.000000,141.000000,123.000000,97.000000,105.000000,89.000000,70.000000,70.000000,34.000000,...,22.000000,11.000000,4.000000,6.000000,6.00000,3.000000,2.000000,2.000000,1.0,1.0
mean,36.028369,33.034483,36.028369,33.390244,36.762887,34.933333,32.438202,33.157143,32.214286,38.588235,...,36.727273,42.090909,39.750000,39.333333,37.00000,33.333333,30.000000,28.000000,20.0,20.0
std,31.292843,15.862414,31.292843,16.265539,15.138784,14.897255,15.910228,15.309025,15.984497,17.050936,...,17.221752,19.185695,5.188127,21.020625,19.61632,11.547005,14.142136,11.313708,NaN,NaN
min,10.000000,10.000000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,11.000000,...,11.000000,12.000000,36.000000,12.000000,12.00000,20.000000,20.000000,20.000000,20.0,20.0
25%,19.000000,21.000000,19.000000,20.000000,25.000000,22.000000,19.000000,21.250000,19.000000,27.250000,...,27.250000,34.500000,36.000000,23.750000,24.00000,30.000000,25.000000,24.000000,20.0,20.0
50%,33.000000,33.000000,33.000000,33.000000,39.000000,36.000000,33.000000,31.500000,29.000000,35.000000,...,37.000000,40.000000,38.000000,41.000000,38.00000,40.000000,30.000000,28.000000,20.0,20.0
75%,45.000000,43.000000,45.000000,45.000000,46.000000,46.000000,43.000000,44.750000,45.000000,47.500000,...,47.750000,55.000000,41.750000,53.000000,45.25000,40.000000,35.000000,32.000000,20.0,20.0
max,353.000000,75.000000,353.000000,75.000000,75.000000,73.000000,75.000000,74.000000,74.000000,73.000000,...,68.000000,72.000000,47.000000,67.000000,67.00000,40.000000,40.000000,36.000000,20.0,20.0

In [132]:
data.isna().sum()

fraudulent                                             0
customer/customerEmail                                 0
customer/customerPhone                                 0
customer/customerDevice                                0
customer/customerIPAddress                             0
customer/customerBillingAddress                        0
orders/0/orderId                                      27
orders/0/orderAmount                                  27
orders/0/orderState                                   27
orders/0/orderShippingAddress                         27
orders/1/orderId                                      52
orders/1/orderAmount                                  52
orders/1/orderState                                   52
orders/1/orderShippingAddress                         52
paymentMethods/0/paymentMethodId                      12
paymentMethods/0/paymentMethodRegistrationFailure     12
paymentMethods/0/paymentMethodType                    12
paymentMethods/0/paymentMethodProvider                12
paymentMethods/0/paymentMethodIssuer                  12
transactions/0/transactionId                          27
transactions/0/orderId                                27
transactions/0/paymentMethodId                        27
transactions/0/transactionAmount                      27
transactions/0/transactionFailed                      27
transactions/1/transactionId                          45
transactions/1/orderId                                45
transactions/1/paymentMethodId                        45
transactions/1/transactionAmount                      45
transactions/1/transactionFailed                      45
orders/2/orderId                                      71
                                                    ...
transactions/9/transactionId                         162
transactions/9/orderId                               162
transactions/9/paymentMethodId                       162
transactions/9/transactionAmount                     162
transactions/9/transactionFailed                     162
transactions/10/transactionId                        165
transactions/10/orderId                              165
transactions/10/paymentMethodId                      165
transactions/10/transactionAmount                    165
transactions/10/transactionFailed                    165
transactions/11/transactionId                        166
transactions/11/orderId                              166
transactions/11/paymentMethodId                      166
transactions/11/transactionAmount                    166
transactions/11/transactionFailed                    166
transactions/12/transactionId                        166
transactions/12/orderId                              166
transactions/12/paymentMethodId                      166
transactions/12/transactionAmount                    166
transactions/12/transactionFailed                    166
transactions/13/transactionId                        167
transactions/13/orderId                              167
transactions/13/paymentMethodId                      167
transactions/13/transactionAmount                    167
transactions/13/transactionFailed                    167
transactions/14/transactionId                        167
transactions/14/orderId                              167
transactions/14/paymentMethodId                      167
transactions/14/transactionAmount                    167
transactions/14/transactionFailed                    167
Length: 188, dtype: int64

In [133]:
data.drop(['transactions/9/transactionId','transactions/9/orderId','transactions/9/paymentMethodId','transactions/9/transactionAmount','transactions/9/transactionFailed','transactions/10/transactionId','transactions/10/orderId','transactions/10/paymentMethodId','transactions/10/transactionAmount','transactions/10/transactionFailed','transactions/11/transactionId','transactions/11/orderId','transactions/11/paymentMethodId','transactions/11/transactionAmount','transactions/11/transactionFailed','transactions/12/transactionId','transactions/12/orderId','transactions/12/paymentMethodId','transactions/12/transactionAmount','transactions/12/transactionFailed','transactions/13/transactionId','transactions/13/orderId','transactions/13/paymentMethodId','transactions/13/transactionAmount','transactions/13/transactionFailed','transactions/14/transactionId','transactions/14/orderId','transactions/14/paymentMethodId','transactions/14/transactionAmount','transactions/14/transactionFailed'],inplace=True,axis=1)

In [134]:
data.drop(['customer/customerEmail','customer/customerPhone','customer/customerDevice','customer/customerIPAddress','customer/customerBillingAddress'],inplace=True,axis=1)

In [135]:
data.columns

Index(['fraudulent', 'orders/0/orderId', 'orders/0/orderAmount',
       'orders/0/orderState', 'orders/0/orderShippingAddress',
       'orders/1/orderId', 'orders/1/orderAmount', 'orders/1/orderState',
       'orders/1/orderShippingAddress', 'paymentMethods/0/paymentMethodId',
       ...
       'paymentMethods/14/paymentMethodIssuer', 'orders/7/orderId',
       'orders/7/orderAmount', 'orders/7/orderState',
       'orders/7/orderShippingAddress', 'transactions/8/transactionId',
       'transactions/8/orderId', 'transactions/8/paymentMethodId',
       'transactions/8/transactionAmount', 'transactions/8/transactionFailed'],
      dtype='object', length=153)

In [136]:
data.isna().sum()

fraudulent                                              0
orders/0/orderId                                       27
orders/0/orderAmount                                   27
orders/0/orderState                                    27
orders/0/orderShippingAddress                          27
orders/1/orderId                                       52
orders/1/orderAmount                                   52
orders/1/orderState                                    52
orders/1/orderShippingAddress                          52
paymentMethods/0/paymentMethodId                       12
paymentMethods/0/paymentMethodRegistrationFailure      12
paymentMethods/0/paymentMethodType                     12
paymentMethods/0/paymentMethodProvider                 12
paymentMethods/0/paymentMethodIssuer                   12
transactions/0/transactionId                           27
transactions/0/orderId                                 27
transactions/0/paymentMethodId                         27
transactions/0/transactionAmount                       27
transactions/0/transactionFailed                       27
transactions/1/transactionId                           45
transactions/1/orderId                                 45
transactions/1/paymentMethodId                         45
transactions/1/transactionAmount                       45
transactions/1/transactionFailed                       45
orders/2/orderId                                       71
orders/2/orderAmount                                   71
orders/2/orderState                                    71
orders/2/orderShippingAddress                          71
paymentMethods/1/paymentMethodId                       89
paymentMethods/1/paymentMethodRegistrationFailure      89
                                                     ...
paymentMethods/10/paymentMethodIssuer                 165
paymentMethods/11/paymentMethodId                     165
paymentMethods/11/paymentMethodRegistrationFailure    165
paymentMethods/11/paymentMethodType                   165
paymentMethods/11/paymentMethodProvider               165
paymentMethods/11/paymentMethodIssuer                 165
paymentMethods/12/paymentMethodId                     165
paymentMethods/12/paymentMethodRegistrationFailure    165
paymentMethods/12/paymentMethodType                   165
paymentMethods/12/paymentMethodProvider               165
paymentMethods/12/paymentMethodIssuer                 165
paymentMethods/13/paymentMethodId                     166
paymentMethods/13/paymentMethodRegistrationFailure    166
paymentMethods/13/paymentMethodType                   166
paymentMethods/13/paymentMethodProvider               166
paymentMethods/13/paymentMethodIssuer                 166
paymentMethods/14/paymentMethodId                     167
paymentMethods/14/paymentMethodRegistrationFailure    167
paymentMethods/14/paymentMethodType                   167
paymentMethods/14/paymentMethodProvider               167
paymentMethods/14/paymentMethodIssuer                 167
orders/7/orderId                                      164
orders/7/orderAmount                                  164
orders/7/orderState                                   164
orders/7/orderShippingAddress                         164
transactions/8/transactionId                          162
transactions/8/orderId                                162
transactions/8/paymentMethodId                        162
transactions/8/transactionAmount                      162
transactions/8/transactionFailed                      162
Length: 153, dtype: int64

In [137]:
data.columns

Index(['fraudulent', 'orders/0/orderId', 'orders/0/orderAmount',
       'orders/0/orderState', 'orders/0/orderShippingAddress',
       'orders/1/orderId', 'orders/1/orderAmount', 'orders/1/orderState',
       'orders/1/orderShippingAddress', 'paymentMethods/0/paymentMethodId',
       ...
       'paymentMethods/14/paymentMethodIssuer', 'orders/7/orderId',
       'orders/7/orderAmount', 'orders/7/orderState',
       'orders/7/orderShippingAddress', 'transactions/8/transactionId',
       'transactions/8/orderId', 'transactions/8/paymentMethodId',
       'transactions/8/transactionAmount', 'transactions/8/transactionFailed'],
      dtype='object', length=153)

In [138]:
data.corr()

,fraudulent,orders/0/orderAmount,orders/1/orderAmount,transactions/0/transactionAmount,transactions/1/transactionAmount,orders/2/orderAmount,transactions/2/transactionAmount,transactions/3/transactionAmount,transactions/4/transactionAmount,orders/3/orderAmount,orders/4/orderAmount,orders/5/orderAmount,orders/6/orderAmount,transactions/5/transactionAmount,transactions/6/transactionAmount,transactions/7/transactionAmount,orders/7/orderAmount,transactions/8/transactionAmount
fraudulent,1.000000,0.275806,0.341027,0.275806,0.333266,0.426187,0.345943,0.418192,0.381850,0.421084,0.218506,NaN,NaN,0.400787,0.398604,0.406663,NaN,0.450575
orders/0/orderAmount,0.275806,1.000000,0.450724,1.000000,0.581739,0.369328,0.433834,0.413295,0.381530,0.428656,0.476333,0.171349,-0.553568,0.395392,0.364805,0.566997,-0.998787,0.376732
orders/1/orderAmount,0.341027,0.450724,1.000000,0.450724,0.894272,0.246264,0.536212,0.345890,0.544581,0.444721,0.583635,0.145502,0.371867,0.511405,0.437442,0.750949,0.145916,0.888392
transactions/0/transactionAmount,0.275806,1.000000,0.450724,1.000000,0.581739,0.369328,0.433834,0.413295,0.381530,0.428656,0.476333,0.171349,-0.553568,0.395392,0.364805,0.566997,-0.998787,0.376732
transactions/1/transactionAmount,0.333266,0.581739,0.894272,0.581739,1.000000,0.316405,0.499141,0.396222,0.629838,0.506748,0.666134,-0.029802,-0.634996,0.507542,0.543830,0.687050,-0.322083,0.734461
orders/2/orderAmount,0.426187,0.369328,0.246264,0.369328,0.316405,1.000000,0.693720,0.682816,0.545337,0.515146,0.378135,0.075723,0.387994,0.533062,0.443937,0.430920,0.289122,0.826593
transactions/2/transactionAmount,0.345943,0.433834,0.536212,0.433834,0.499141,0.693720,1.000000,0.470620,0.542733,0.495246,0.352425,-0.198469,0.121597,0.453598,0.300304,0.298239,-0.074854,0.862547
transactions/3/transactionAmount,0.418192,0.413295,0.345890,0.413295,0.396222,0.682816,0.470620,1.000000,0.621463,0.703776,0.426426,0.105365,0.902772,0.416038,0.444913,0.375794,0.060272,0.884079
transactions/4/transactionAmount,0.381850,0.381530,0.544581,0.381530,0.629838,0.545337,0.542733,0.621463,1.000000,0.929662,0.769270,0.664760,-0.049124,0.760146,0.624791,0.819680,0.744285,0.906584
orders/3/orderAmount,0.421084,0.428656,0.444721,0.428656,0.506748,0.515146,0.495246,0.703776,0.929662,1.000000,0.696145,0.714104,0.668865,0.830401,0.767617,0.764988,0.651619,0.943661
orders/4/orderAmount,0.218506,0.476333,0.583635,0.476333,0.666134,0.378135,0.352425,0.426426,0.769270,0.696145,1.000000,0.262230,-0.139358,0.875953,0.793341,0.638500,0.560607,0.822629
orders/5/orderAmount,NaN,0.171349,0.145502,0.171349,-0.029802,0.075723,-0.198469,0.105365,0.664760,0.714104,0.262230,1.000000,0.122365,0.308978,0.371014,0.998465,0.110518,0.501602
orders/6/orderAmount,NaN,-0.553568,0.371867,-0.553568,-0.634996,0.387994,0.121597,0.902772,-0.049124,0.668865,-0.139358,0.122365,1.000000,0.307863,0.587859,0.419029,0.494902,0.991290
transactions/5/transactionAmount,0.400787,0.395392,0.511405,0.395392,0.507542,0.533062,0.453598,0.416038,0.760146,0.830401,0.875953,0.308978,0.307863,1.000000,0.772816,0.754199,0.758124,0.893981
transactions/6/transactionAmount,0.398604,0.364805,0.437442,0.364805,0.543830,0.443937,0.300304,0.444913,0.624791,0.767617,0.793341,0.371014,0.587859,0.772816,1.000000,0.675153,0.274976,0.761679
transactions/7/transactionAmount,0.406663,0.566997,0.750949,0.566997,0.687050,0.430920,0.298239,0.375794,0.819680,0.764988,0.638500,0.998465,0.419029,0.754199,0.675153,1.000000,0.169942,0.800066
orders/7/orderAmount,NaN,-0.998787,0.145916,-0.998787,-0.322083,0.289122,-0.074854,0.060272,0.744285,0.651619,0.560607,0.110518,0.494902,0.758124,0.274976,0.169942,1.000000,0.515292
transactions/8/transactionAmount,0.450575,0.376732,0.888392,0.376732,0.734461,0.826593,0.862547,0.884079,0.906584,0.943661,0.822629,0.501602,0.991290,0.893981,0.761679,0.800066,0.515292,1.000000

In [139]:
x=['orders/0/orderAmount','orders/1/orderAmount','transactions/0/transactionAmount',
   'transactions/1/transactionAmount','orders/2/orderAmount','transactions/2/transactionAmount',
   'transactions/3/transactionAmount','transactions/4/transactionAmount','orders/3/orderAmount',
   'orders/4/orderAmount','transactions/5/transactionAmount','transactions/6/transactionAmount',
   'transactions/7/transactionAmount','transactions/8/transactionAmoun']

In [140]:
from sklearn.preprocessing import OneHotEncoder

In [141]:
from sklearn.preprocessing import LabelEncoder
number = LabelEncoder()

In [142]:
data['transactions/8/transactionAmount'].value_counts()

12.0    1
20.0    1
35.0    1
47.0    1
55.0    1
67.0    1
Name: transactions/8/transactionAmount, dtype: int64

In [143]:
data['orders/1/orderId'].fillna('1',inplace=True)
data['orders/1/orderAmount'].fillna('6',inplace=True)
data['transactions/0/transactionAmount'].fillna('6',inplace=True)
data['orders/0/orderAmount'].fillna('1',inplace=True)
data['orders/0/orderState'].fillna('fulfilled',inplace=True)
data['orders/0/orderId'].fillna('1',inplace=True)
data['transactions/1/transactionAmount'].fillna('6',inplace=True)
data['orders/2/orderAmount'].fillna('6',inplace=True)
data['transactions/2/transactionAmount'].fillna('5',inplace=True)
data['transactions/3/transactionAmount'].fillna('5',inplace=True)
data['transactions/4/transactionAmount'].fillna('5',inplace=True)
data['orders/3/orderAmount'].fillna('3',inplace=True)
data['orders/4/orderAmount'].fillna('2',inplace=True)
data['transactions/5/transactionAmount'].fillna('3',inplace=True)
data['transactions/6/transactionAmount'].fillna('2',inplace=True)
data['transactions/7/transactionAmount'].fillna('2',inplace=True)
data['transactions/8/transactionAmount'].fillna('1',inplace=True)

In [144]:
from sklearn.preprocessing import LabelEncoder
number = LabelEncoder()

In [145]:
feat=['orders/0/orderAmount','orders/1/orderAmount','transactions/0/transactionAmount',
   'transactions/1/transactionAmount','orders/2/orderAmount','transactions/2/transactionAmount',
   'transactions/3/transactionAmount','transactions/4/transactionAmount','orders/3/orderAmount',
   'orders/4/orderAmount','transactions/5/transactionAmount','transactions/6/transactionAmount',
   'transactions/7/transactionAmount','transactions/8/transactionAmount']
X=data[feat]
y = data.fraudulent

In [146]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=None)

In [147]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression() 
logreg.fit(x_train, y_train)

C:\Users\vvgls\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [148]:
y_pred = logreg.predict(x_test) 
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(x_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.82

In [149]:
y_pred

array([False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False])

In [150]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.80      1.00      0.89        12
        True       1.00      0.40      0.57         5

   micro avg       0.82      0.82      0.82        17
   macro avg       0.90      0.70      0.73        17
weighted avg       0.86      0.82      0.80        17